---
- hosts: ios
  connection: network_cli
  gather_facts: yes

  tasks:
    - name: Configure the interface
      ios_config:
        lines:
          - ip address 10.0.10.11 255.255.255.0
          - no shutdown
        parents:
          - interface FastEthernet0/1

    - name: Waiting for carrier-delay
      pause:
        seconds: 5

    - name: Collecting operation information from '{{ ansible_network_os }}'
      ios_command:
        commands:
          - show ip interface brief
      register: ios_output

    - name: Verification of the output
      debug:
        msg: "{{ ios_output.stdout_lines }}"